# Predicting on new data

In [1]:
# As usual we are starting a new notebook and we need to import all relevant packages
import numpy as np
import tensorflow as tf
import pickle

In [2]:
# To load the scaler we use the pickle method load
scaler_deep_learning = pickle.load(open('scaler_deep_learning.pickle', 'rb'))
# To load the model, we use the TensorFlow (Keras) function relevant for the operation
model = tf.keras.models.load_model('audiobooks_model.h5')

# Note that since we did not specify the input shape of our inputs in the modeling part, we get a warning
# For feed-forward neural networks such as ours that is not an issue

## Loading the new data

In [3]:
# The new data is located in 'New_Audiobooks_Data.csv'
# To keep everything as before, we must specify the delimiter explicitly
raw_data = np.loadtxt('New_Audiobooks_Data.csv',delimiter=',')
# We are interested in all data except for the first column (ID)
# Note that there are no targets in this CSV file (we don't know the behavior of these clients, yet!)
new_data_inputs = raw_data[:,1:]
# new_data_inputs = np.reshape([1188,5.33,0,8.91,0.12,0,0])

In [4]:
new_data_inputs

array([[1.1880e+03, 1.1880e+03, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 1.2000e-01, 0.0000e+00, 0.0000e+00, 3.9000e+01],
       [6.4800e+02, 6.4800e+02, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 4.8000e-01, 0.0000e+00, 0.0000e+00, 9.1000e+01],
       [2.1600e+03, 2.1600e+03, 7.6900e+00, 7.6900e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 6.8040e+02, 0.0000e+00, 0.0000e+00],
       [1.6740e+03, 3.3480e+03, 8.0000e+00, 1.6000e+01, 1.0000e+00,
        1.0000e+01, 0.0000e+00, 0.0000e+00, 0.0000e+00, 2.7000e+01],
       [2.1600e+03, 2.1600e+03, 5.6600e+00, 5.6600e+00, 0.0000e+00,
        8.9100e+00, 1.2000e-01, 7.3440e+02, 0.0000e+00, 1.9800e+02],
       [2.1600e+03, 2.1600e+03, 6.5800e+00, 6.5800e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 7.3440e+02, 0.0000e+00, 0.0000e+00],
       [2.1600e+03, 2.1600e+03, 5.3300e+00, 5.3300e+00, 0.0000e+00,
        8.9100e+00, 0.0000e+00, 6.8040e+02, 0.0000e+00, 0.0000e+00],
       [2.1600e+03, 2.1600e+03, 7.9300e+0

## Predict the probability of a customer to convert

In [5]:
# Scale the new data in the same way we scaled the train data
new_data_inputs_scaled = scaler_deep_learning.transform(new_data_inputs)


In [6]:
# Predict the probability of each customer to convert
# Here we have also taken only the second column and rounded to 2 digits after the dot
model.predict(new_data_inputs_scaled)[:,1].round(2)


array([0.02, 0.  , 0.06, 1.  , 0.  , 0.04, 0.04, 0.04, 0.03, 0.78, 0.  ,
       0.85, 0.96, 0.  , 0.13, 0.16, 0.91, 0.75, 0.9 , 0.97, 1.  , 1.  ,
       1.  , 0.  , 0.  , 1.  , 0.58, 0.  , 1.  , 1.  ], dtype=float32)

In [7]:
# Implement the better approach which is independent of the number of classes
np.argmax(model.predict(new_data_inputs_scaled),1)

array([0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 1, 1,
       1, 0, 0, 1, 1, 0, 1, 1], dtype=int64)

In [9]:
# model.predict([1188,1188,5.33,5.33,0,8.91,0.12,0,0,39])
# model.predict(np.reshape([1188,1188,5.33,5.33,0,8.91,0.12,0,0,39], (1,-1)))
scaled = scaler_deep_learning.transform(np.reshape([1674,3348,8,16,1,10,0,0,0,27], (1,-1)))
# np.argmax(model.predict(np.reshape([1188,1188,5.33,5.33,0,8.91,0.12,0,0,39], (1,-1))),1)
pred =np.argmax(model.predict(scaled),1)

In [12]:
float(pred)

1.0